# Generated by Django 5.2.6 on 2025-10-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_businessprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='updated_at',
        ),
    ]
